name: build-and-test-auth-app

on:
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'
      - 'package-lock.json'
      - 'apps/auth/**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Build & Test
        run: |
          cd apps/auth
          npm install
          npm run lint
          npm run build
